### ISSUE TITLE
CSS Selectors Changed in 5.0

### ISSUE THREAD

**Issue by Riolku** [catppuccin/sidebery#5]
As of a few days ago, it seems Sidebery upgraded to version 5.0. Debug Info tells me I have sidebery 5.0 and firefox 117.0.1.

Styles do not apply cleanly, from what I can tell, and some features have been added which conflict with our current styling.

Can anyone else confirm this?

**Comment by johanohly** [comment]
Sidebery 5.0 supports firefox color, so my understanding is, that this is redundant

**Comment by thismoon** [comment]
As johnny said, sidebery now automatically takes the colors from [the Firefox theme](https://github.com/catppuccin/firefox). So the theme is redundant now.
I am going to archive this repository.
